[package]
name = "splits-io"
version = "0.1.0"
authors = ["Cris Hall-Ramos <crishallramos@yahoo.com>"]

[dependencies]
serde = "1.0.27"
serde_json = "1.0.9"
serde_derive = "1.0.27"

hyper = "0.11.18"
hyper-tls = "0.1.2"
futures = "0.1.18"
tokio-core = "0.1.12"

[dev-dependencies]
tokio = "0.1.1"
